spring:
  datasource:
    username: root
    password: root
    url: jdbc:mysql://localhost:3306/cloudenergy_x?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver

mybatis:
  typeAliasesPackage: com.example.socket.entity
  mapperLocations: classpath:mapper/*.xml

logging:
  path: socketLog:/log
  file: socketlogs.log

#tcp端口
tcp:
  port: 8888
# bossGroup线程数
boss:
  thread:
    count: 5
# worker线程数
worker:
  thread:
    count: 5
#长连接
so:
  keepalive:  true
  backlog: 10


